In [1]:
import numpy as np

### Задание 1
Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).


In [2]:
n = 10

In [12]:
np.arange(n-1,-1,-1)

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

### Задание 2
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.



In [8]:
np.sum(np.diag(np.arange(n-1,-1,-1)))

45

### Задание 3
Решите систему уравнений:  
4x + 2y + z = 4  
x + 3y = 12  
5y + 4z = -3


In [11]:
a = [[4, 2, 1],
     [1, 3, 0],
     [0, 5, 4]]

b = [4, 12, -3]

np.linalg.solve(a, b)

array([ 0.46666667,  3.84444444, -5.55555556])

### Задание 4
Имеется матрица покупок в интернет-магазине. Столбец А - ID пользователя. Остальные столбцы - количество покупок категорий товаров этим пользователем:

In [21]:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)

На сайт заходит очередной посетитель, о покупках которого известно следующее:

In [22]:
next_user_stats = np.array([0, 1, 2, 0, 0, 0])

Найдите самого похожего пользователя. Т. е. посчитайте косинусное сходство между этим пользователем и всеми пользователями из массива user_stats

In [25]:
def cosine( a, b ):
    aLength = np.linalg.norm( a )
    bLength = np.linalg.norm( b )
    return np.dot( a, b ) / ( aLength * bLength )

the_most_similar = []
max_ = 0 
for user in users_stats:
    if cosine(next_user_stats, user) > max_:
            max_ = cosine(next_user_stats, user)
            the_most_similar = user
print(the_most_similar)

[0 1 1 0 0 0]
